#!/usr/bin/env ruby

paths = [
  '~/.bash_aliases',
  '~/.bashrc',
  '~/.bash_profile',
  '~/.git-completion.bash',
  '~/.gitconfig',
  '~/.gitignore',
  '~/.tmux.conf',
  '~/.rspec',
  '~/.zshrc',
]

paths.each do |path|
  if File.exist?(File.expand_path(path))
    puts "Copying #{path} to ."
    `cp #{path} .`
  end
end