#!/usr/bin/env ruby

paths = [
  '~/.bash_aliases',
  '~/.bashrc',
  '~/.bash_profile',
  '~/.git-completion.sh',
  '~/.gitconfig',
  '~/.gitignore',
  '~/.tmux.conf',
  '~/.rspec'
]

paths.each do |path|
  `cp #{path} .`
end