#!/usr/bin/env ruby
# Usage: ./script/install to install these files to their locations on the filesystem

require 'fileutils'

paths = [
  '.bash_aliases',
  '.bashrc',
  '.bash_profile',
  '.git-completion.bash',
  '.gitconfig',
  '.gitignore',
  '.tmux.conf',
  '.rspec',
  '.zshrc',
]

paths.each do |path|
  dest_path = File.expand_path("~/#{path}")
  src_path  = File.expand_path("./#{path}")
  if File.exists?(dest_path)
    backup_path = File.expand_path("#{dest_path}.bk")
    puts "Existing #{path} file found. Creating backup at #{backup_path}"
    FileUtils.cp(dest_path, backup_path)
  end

  puts "Copying #{src_path} -> #{dest_path}"
  FileUtils.cp(src_path, dest_path)
end

# install git hooks

git_hooks_path = File.expand_path("./git-hooks")
git_hooks_dest_path = File.expand_path("~/.git-hooks")
if File.exists?(git_hooks_dest_path)
  backup_path = File.expand_path("#{git_hooks_dest_path}.bk")
  puts "Existing git-hooks directory found. Creating backup at #{backup_path}"
  FileUtils.cp_r(git_hooks_dest_path, backup_path)
else
  FileUtils.mkdir_p(git_hooks_dest_path)
  FileUtils.cp_r(git_hooks_path, git_hooks_dest_path)
end